# Generated by Django 6.0.4 on 2026-04-30 02:02

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracaoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cooperative_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('country', django_countries.fields.CountryField(blank=True, default='Togo', max_length=2, null=True)),
                ('city', models.CharField(blank=True, default='Lome', max_length=100, null=True)),
                ('is_transporter', models.BooleanField(default=False)),
                ('is_producer', models.BooleanField(default=False)),
                ('is_cooperative_source', models.BooleanField(default=False)),
                ('is_cooperative_destination', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('id_picture', models.ImageField(blank=True, null=True, upload_to='id_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.ForeignKey(limit_choices_to={'is_cooperative_source': True}, on_delete=django.db.models.deletion.CASCADE, related_name='origin_stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.ForeignKey(limit_choices_to={'is_cooperative_destination': True}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_destination_stocks', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(limit_choices_to={'is_transporter': True}, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_stocks', to=settings.AUTH_USER_MODEL)),
                ('stock_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_records', to='user.stockorigin')),
            ],
        ),
        migrations.CreateModel(
            name='StockProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('product_type', models.CharField(choices=[('cacao', 'Cacao'), ('cafe', 'Cafe')], max_length=100)),
                ('species', models.TextField(blank=True, null=True)),
                ('origin', models.CharField(max_length=200)),
                ('surface_size', models.FloatField()),
                ('production_size', models.FloatField()),
                ('cooperative', models.ForeignKey(limit_choices_to={'is_cooperative_source': True}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_source_stocks', to=settings.AUTH_USER_MODEL)),
                ('producer', models.ForeignKey(limit_choices_to={'is_producer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='producer_stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockorigin',
            name='producer_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_records', to='user.stockproducer'),
        ),
        migrations.CreateModel(
            name='StockTransporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.ForeignKey(limit_choices_to={'is_cooperative_destination': True}, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_destination_transports', to=settings.AUTH_USER_MODEL)),
                ('stock_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_records', to='user.stockorigin')),
                ('transporter', models.ForeignKey(limit_choices_to={'is_transporter': True}, on_delete=django.db.models.deletion.CASCADE, related_name='transported_stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
