# Generated by Django 6.0.4 on 2026-04-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracaouser',
            name='is_staff',
        ),
    ]
