# Generated by Django 6.0.4 on 2026-04-26 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tracaouser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracaouser',
            name='is_staff',
        ),
    ]
