# Generated by Django 6.0.4 on 2026-04-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_tracaouser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracaouser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
